name: gitlint

on:
  push:
  pull_request:

jobs:
  checks:
    runs-on: "ubuntu-latest"

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.even.pull_request.head.sha }} # Checkout pull request HEAD commit instead of merge commit
        fetch-depth: 0 # fetch complete history

    - uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Install gitlint
      run: pip install gitlint

    - name: Run gitlint
      run: |
        if [[ -z "${GITHUB_BASE_REF}" ]]; then
          BASE=origin/master
        else
          BASE="${GITHUB_BASE_REF}"
        fi
        echo "Linting: ${BASE}..${GITHUB_HEAD_REF}"
        gitlint --commits ${BASE}..${GITHUB_HEAD_REF}
